//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P4FLauncher.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("P4FLauncher.Resources.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 07/01/2019_ 402 
        ///.
        /// </summary>
        internal static string BuildDate {
            get {
                return ResourceManager.GetString("BuildDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +webSiteHostName &quot;#IP#&quot; +battleFundsHostName &quot;#IP#&quot; +survey 0 +dc 1 +sessionId #SESSION# +lang en +soldierName &quot;#PLAYER#&quot; +multi 1 +frontendUrl &quot;http://#IP#:1234/&quot; +autoLogin 1 +loggedIn &quot;true&quot; +webBrowser 0 +magmaProtocol http +magmaHost #IP# +punkBuster 0.
        /// </summary>
        internal static string client_startup {
            get {
                return ResourceManager.GetString("client_startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] redi {
            get {
                object obj = ResourceManager.GetObject("redi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #IP#    jeff.easylocaldev.com
        ///#IP#    battlefield.play4free.com
        ///#IP#    dev.easy.ea.com
        ///#IP#    dev2.easy.ea.com
        ///#IP#    dev3.easy.ea.com
        ///#IP#    dev4.easy.ea.com
        ///#IP#    playtest1.easy.ea.com
        ///#IP#    playtest1.easy.ea.com
        ///#IP#    private.battlefield.play4free.com
        ///#IP#    preprod.battlefield.play4free.com
        ///#IP#    pte.battlefield.play4free.com
        ///#IP#    gosredirector.ea.com
        ///#IP#    peach.online.ea.com
        ///#IP#    nexus.passport.com.
        /// </summary>
        internal static string template_hosts_file {
            get {
                return ResourceManager.GetString("template_hosts_file", resourceCulture);
            }
        }
    }
}
